AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lentics-shipstation

  Sample SAM Template for lentics-shipstation

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 840

Resources:
  ShipstationAutomationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: shipstation_automation/app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: cron(30 10 ? * MON,TUE,WED,THU,FRI,SUN *)  # 10:30 AM UTC Mon-Fri,Sun
            Description: "Triggers function to run on the specfied timer schedule"
