AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lentics-shipstation

  Sample SAM Template for lentics-shipstation

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 840

Resources:
  ShipstationAutomationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: shipstation_automation/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
