version: 1
disable_existing_loggers: false

formatters:
  detailed: &detailed_formatter
    format: '[%(asctime)s] %(levelname)s - %(name)s:%(funcName)s:%(lineno)d - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  simple: &simple_formatter
    format: '%(levelname)s - %(message)s'

handlers:
  file: &file_handler
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/app.log
    maxBytes: 5242880  # 5MB
    backupCount: 2
    encoding: utf8
