version: 1
disable_existing_loggers: false

formatters:
  simple:
    '()': shipstation_automation.utils.logger.ColorAwareFormatter
    format: '%(message)s'
  
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

  lambda:
    format: '[%(levelname)s] %(name)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: lambda
    stream: ext://sys.stdout
  
  file:
    class: logging.FileHandler
    level: INFO
    formatter: detailed
    filename: logs/development.log
    mode: 'a'

loggers:
  shipstation_automation:  # Core application logs
    level: INFO
    handlers: [console, file]
    propagate: false
    
  shipstation_automation.debug:  # Development debugging
    level: DEBUG
    handlers: [console, file]
    propagate: false

root:
  level: INFO
  handlers: [console, file]
  propagate: false
