version: 1
disable_existing_loggers: false

formatters:
  standard:
    '()': shipstation_automation.utils.logger.ColorAwareFormatter
    format: '[%(levelname)s] %(name)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout
  
  file:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: logs/app.log
    mode: 'a'

loggers:
  shipstation_automation:
    level: INFO
    handlers: [console, file]
    propagate: false

root:
  level: INFO
  handlers: [console, file]
  propagate: false